# Generated by Django 4.2.3 on 2023-07-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petstagramuser',
            name='gender',
            field=models.CharField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'DO_NOT_SHOW')], max_length=11),
        ),
        migrations.AlterField(
            model_name='petstagramuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
