# Generated by Django 4.2.3 on 2023-07-22 14:14

from django.db import migrations, models
import petstagram.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_petstagramuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petstagramuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], default=petstagram.accounts.models.Gender['DO_NOT_SHOW'], max_length=11),
        ),
    ]
